apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-node-app-stg
  namespace: default
  spec:
  replicas: 4
  selector:
    matchLabels:
      app: sample-node-app-stg
  template:
    metadata:
      labels:
        app: sample-node-app-stg
    spec:
      containers:
      - name: sample-node-app-stg
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: sample-node-app-stg
  ports:
    - port: 80 
      targetPort: 8000  