apiVersion: v1
kind: Service
metadata:
 name: {{ .Values.service }}
 namespace: {{ .Values.namespace }}
spec:
 selector:
   app: {{ .Values.label }}
 ports:
 - port: 80
   targetPort: 3000
   protocol: TCP
 type: ClusterIP
