apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-node-app-prd
  namespace: default
  spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-node-app-prd
  template:
    metadata:
      labels:
        app: sample-node-app-prd
    spec:
      containers:
      - name: sample-node-app-prd
        image: kunalmac25/node-image
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: sample-node-app-prd
  ports:
    - port: 80 
      targetPort: 8000  