apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 'appset-generator-prd2'
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/Waji-97/ArgoCD-Test.git
              revision: HEAD
              directories:
                - path: 'envs/prd/*'
                - path: 'envs/prd/note'
                  exclude: true
                - path: 'envs/prd/argocd'
                  exclude: true
                - path: 'envs/prd/values'
                  exclude: true
          - clusters:
              selector:
                matchLabels:
                  ctype: prd
  template:      
    metadata:
      name: 'app-generated-{{path[1]}}-{{path[2]}}-{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: default
      source:
        repoURL: https://github.com/Waji-97/ArgoCD-Test.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
          - "../values/{{path[2]}}-{{name}}-values.yaml"
      destination:
        server: '{{server}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated: 
          selfHeal: true
